// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "1bb47314-bde8-4919-8583-c61d2feeb092");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1538024992);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1538024962);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.asrouterOnboardingCohort", 2);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"25197\":1538024964996,\"25200\":1538024964996,\"25204\":1538024964996}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"689\":[1538024965019]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{76b92c21-835e-4930-9241-bb3c089436e3}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1538024400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1538024966);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1538024966632");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1538028566632");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1538024964");
user_pref("browser.slowStartup.averageTime", 2614);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20180920131237");
user_pref("browser.startup.homepage_override.mstone", "62.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"firefoxcolor_mozilla_com-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\",\"firefoxcolor_mozilla_com-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1538024965646");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "62.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "62.0.2");
user_pref("extensions.lastPlatformVersion", "62.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"a72ae2b7-6e29-4a02-9801-07135246f4dd\",\"screenshots@mozilla.org\":\"66624da8-1717-4d9b-a3ae-1911822ee086\",\"FirefoxColor@mozilla.com\":\"b17d0618-e22b-4f0c-b457-f627d9eb3e4a\"}");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("lightweightThemes.persisted.footerURL", false);
user_pref("lightweightThemes.persisted.headerURL", false);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x0a16");
user_pref("sanity-test.driver-version", "10.18.14.4264");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20180920131237");
user_pref("security.sandbox.content.tempDirSuffix", "{df197637-f3a4-4a02-8e4b-f1ee0b6714cb}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1538024960);
user_pref("toolkit.telemetry.cachedClientID", "e1626c3b-2be6-4f87-905a-87a1938a25ec");
user_pref("toolkit.telemetry.previousBuildID", "20180920131237");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
